import { describe, expect, it } from "bun:test";
import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  genDependencyGraph,
  genServiceMap,
  genSystemOverview,
} from "../../src/agents/architecture.ts";
import { forgeBlueprint } from "../../src/agents/blueprint-architect.ts";
import { reviseBlueprint } from "../../src/agents/blueprint-reviser.ts";
import {
  genAcceptance,
  genApiContract,
  genBuildTasks,
  genDataModel,
  genDependencies,
  genEvents,
  genServiceBlueprint,
  genServiceSpark,
} from "../../src/agents/per-service.ts";
import { runQaReview } from "../../src/agents/qa-reviewer.ts";
import { renderBlueprintMd, renderQaReviewMd } from "../../src/agents/renderers.ts";
import { writeSpark } from "../../src/brainstorm/spec-writer.ts";
import { DEFAULT_CONFIG } from "../../src/config/schema.ts";
import { buildRegistry, renderRegistryMd } from "../../src/core/registry.ts";
import type { Blueprint, Spark } from "../../src/core/types.ts";
import { verify } from "../../src/core/verify.ts";
import { LLMRouter } from "../../src/llm/router.ts";
import { writeFileSafe } from "../../src/util/fs.ts";
import { MockProvider } from "../fixtures/mock-llm.ts";

/**
 * End-to-end pipeline against a mock LLM. We drive each phase manually so we
 * can assert the per-phase output independently of the orchestrator.
 *
 * The mock returns a deterministic Blueprint with two services, then per-service
 * markdown stubs. The final assertion runs `verify()` over the produced tree.
 */

const MOCK_BLUEPRINT: Blueprint = {
  schemaVersion: 1,
  frozenAt: "2026-05-06T00:00:00Z",
  sparkSlug: "calm-todo",
  summary: "A small calm todo foundation with auth and tasks.",
  architectureStyle: "modular-monolith",
  services: [
    {
      id: "auth",
      name: "Auth",
      purpose: "User identity",
      responsibilities: ["sign-in", "sessions"],
      nonResponsibilities: ["billing"],
      priority: "p0",
      domain: "platform",
      dependsOn: [],
      emitsEvents: false,
      publicApi: true,
      securityCritical: true,
    },
    {
      id: "tasks",
      name: "Tasks",
      purpose: "Task CRUD",
      responsibilities: ["task crud", "lists"],
      nonResponsibilities: ["search"],
      priority: "p0",
      domain: "core",
      dependsOn: ["auth"],
      emitsEvents: false,
      publicApi: true,
      securityCritical: false,
    },
  ],
  crossCutting: {
    auth: "JWT",
    observability: "Pino + OTel",
    deployment: "Docker, single binary",
    dataStore: "SQLite",
    eventBus: null,
  },
  hasUi: true,
  hasResearch: false,
  acceptance: ["A user can sign in", "A user can create and list tasks"],
  buildSequence: ["auth", "tasks"],
};

describe("e2e: pipeline against mock LLM", () => {
  it("produces a verify()-clean docs tree", async () => {
    const out = await mkdtemp(join(tmpdir(), "architect-e2e-"));

    const mock = new MockProvider({ text: "stub" });
    // Blueprint forge → return JSON
    mock.onContains("Produce the Blueprint as JSON", {
      text: JSON.stringify(MOCK_BLUEPRINT),
      json: MOCK_BLUEPRINT,
    });
    // Blueprint reviser → return identical JSON
    mock.onContains("Apply blockers and majors", {
      text: JSON.stringify(MOCK_BLUEPRINT),
      json: MOCK_BLUEPRINT,
    });
    // QA reviewer → return a single-finding response per perspective
    mock.onContains("adversarial QA reviewer", {
      text: JSON.stringify({ findings: [] }),
      json: { findings: [] },
    });
    // Architecture
    mock.onContains("system-overview.md", { text: "# System Overview\n\nGenerated by mock.\n" });
    mock.onContains("service-map.md", { text: "# Service Map\n\n| id |\n|---|\n| auth |\n" });

    // Per-service: each call mentions the kind in its instruction
    mock.onContains("Write the per-service spark.md", {
      text: "# Spark — service\n\nMock spark.\n",
    });
    mock.onContains("Write the per-service blueprint.md", {
      text: "# Blueprint — service\n\nMock blueprint.\n",
    });
    mock.onContains("Write api-contract.md", { text: "# API Contract\n\nMock.\n" });
    mock.onContains("Write data-model.md", { text: "# Data Model\n\nMock.\n" });
    mock.onContains("Write events.md", { text: "# Events\n\n_Not applicable._\n" });
    mock.onContains("Write build-tasks.md", { text: "# Build Tasks\n\n1. Mock task\n" });
    mock.onContains("Write acceptance.md", { text: "# Acceptance\n\nMock.\n" });
    mock.onContains("Write dependencies.md", { text: "# Dependencies\n\nMock.\n" });

    // Cross-service consistency: empty findings
    mock.onContains("cross-service consistency", {
      text: JSON.stringify({ findings: [] }),
      json: { findings: [] },
    });
    // Event map (deterministic — but we still need a fallback for the LLM call when bus exists)
    mock.onContains("docs/architecture/event-map.md", { text: "# Event Map\n\nNone.\n" });

    const cfg = {
      ...DEFAULT_CONFIG,
      models: {
        ...DEFAULT_CONFIG.models,
        strategic: "mock/strategic",
        execution: "mock/execution",
        ui: "mock/ui",
        ensemble: ["mock/ens-1", "mock/ens-2"],
      },
    };
    const router = new LLMRouter(cfg, { mock });

    // Phase 0: Spark
    const spark: Spark = {
      slug: "calm-todo",
      pitch: "A small calm todo app.",
      audience: ["Indie hackers"],
      identity: ["Calm UX", "Local-first"],
      nonGoals: ["Team mode"],
      references: [],
      prose: "—",
      source: "file",
      frozenAt: "2026-05-06T00:00:00Z",
    };
    await writeFileSafe(join(out, "docs/spark.md"), writeSpark(spark));

    // Phase 1: Blueprint
    const draft = await forgeBlueprint(router, spark, []);
    await writeFileSafe(join(out, "docs/blueprint.draft.md"), renderBlueprintMd(draft));

    // Phase 2: QA review
    const reviews = await runQaReview(router, draft);
    await writeFileSafe(join(out, "docs/qa/blueprint-review.md"), renderQaReviewMd(reviews));

    // Phase 3: Revise
    const blueprint = await reviseBlueprint(router, draft, reviews);
    await writeFileSafe(join(out, "docs/blueprint.md"), renderBlueprintMd(blueprint));

    // Phase 4: Architecture
    await writeFileSafe(
      join(out, "docs/architecture/system-overview.md"),
      await genSystemOverview(router, blueprint),
    );
    await writeFileSafe(
      join(out, "docs/architecture/service-map.md"),
      await genServiceMap(router, blueprint),
    );
    await writeFileSafe(
      join(out, "docs/architecture/dependency-graph.md"),
      await genDependencyGraph(router, blueprint),
    );
    await writeFileSafe(join(out, "docs/architecture/event-map.md"), "# Event Map\n\nNone.\n");

    // Phase 5: per-service fanout
    for (const service of blueprint.services) {
      const dir = join(out, service.domain, service.id, "docs");
      const args = { router, spark, blueprint, service };
      await writeFileSafe(join(dir, "spark.md"), await genServiceSpark(args));
      await writeFileSafe(join(dir, "blueprint.md"), await genServiceBlueprint(args));
      await writeFileSafe(join(dir, "api-contract.md"), await genApiContract(args));
      await writeFileSafe(join(dir, "data-model.md"), await genDataModel(args));
      await writeFileSafe(join(dir, "events.md"), await genEvents(args));
      await writeFileSafe(join(dir, "build-tasks.md"), await genBuildTasks(args));
      await writeFileSafe(join(dir, "acceptance.md"), await genAcceptance(args));
      await writeFileSafe(join(dir, "dependencies.md"), await genDependencies(args));
    }

    // Phase 7: registry (skip Phase 6 which we represent via cross-service mock)
    const entries = await buildRegistry(out, { phase: 7 });
    await writeFileSafe(join(out, "docs/doc-registry.md"), renderRegistryMd(entries));

    // Verify
    const result = await verify(out);
    if (!result.ok) {
      console.log("violations:", result.violations);
    }
    expect(result.ok).toBe(true);
    expect(result.checked).toBeGreaterThanOrEqual(2 * 8 + 7); // 2 services × 8 + root docs
    // Spot-check files
    expect(await readFile(join(out, "docs/spark.md"), "utf8")).toContain("calm-todo");
    expect(await readFile(join(out, "docs/blueprint.md"), "utf8")).toContain("`auth`");
    expect(await readFile(join(out, "platform/auth/docs/api-contract.md"), "utf8")).toContain(
      "API Contract",
    );
    expect(await readFile(join(out, "core/tasks/docs/build-tasks.md"), "utf8")).toContain(
      "Build Tasks",
    );
  });
});
