import { readFile, readdir } from "node:fs/promises";
import { join, relative } from "node:path";
import { sha256 } from "../util/fs.ts";
import { joinUnix } from "../util/fs.ts";
import type { RegistryEntry } from "./types.ts";

/**
 * Build the deterministic doc registry for an output directory by walking it,
 * matching every .md file against the per-scope whitelist, and computing SHA-256.
 *
 * Hard rules (enforced by verify.ts using this output):
 *   - Every .md under {out}/docs or {out}/<svc>/docs must appear in the registry.
 *   - The per-service docs whitelist is fixed (8 files; events.md is conditional).
 *   - No .md under <svc>/src.
 */

export const ROOT_DOCS_WHITELIST = [
  "spark.md",
  "blueprint.md",
  "blueprint.draft.md",
  "doc-registry.md",
  "architecture/system-overview.md",
  "architecture/service-map.md",
  "architecture/dependency-graph.md",
  "architecture/event-map.md",
  "qa/blueprint-review.md",
  "qa/cross-service-review.md",
  "qa/security-review.md",
  "qa/production-readiness.md",
  "research/findings.md",
  "ui/wireframe-index.md",
  "ui/user-flows.md",
  "ui/screen-contracts.md",
] as const;

export const SERVICE_DOCS_WHITELIST = [
  "spark.md",
  "blueprint.md",
  "api-contract.md",
  "data-model.md",
  "events.md",
  "build-tasks.md",
  "acceptance.md",
  "dependencies.md",
] as const;

export interface BuildRegistryOptions {
  /** Phase number → assigned to entries written this phase. */
  phase?: number;
}

export async function buildRegistry(
  outDir: string,
  opts: BuildRegistryOptions = {},
): Promise<RegistryEntry[]> {
  const entries: RegistryEntry[] = [];

  // Root docs/
  const rootDocs = join(outDir, "docs");
  for await (const file of walkMd(rootDocs)) {
    const rel = joinUnix(relative(rootDocs, file));
    const kind = inferKindFromRoot(rel);
    if (!kind) continue; // skip files outside whitelist (verify.ts will flag)
    const content = await readFile(file, "utf8");
    entries.push({
      path: joinUnix("docs", rel),
      scope: kind.scope,
      kind: kind.kind,
      phase: opts.phase ?? 0,
      sha256: sha256(content),
      generatedAt: new Date().toISOString(),
    });
  }

  // Per-service <svc>/docs/
  const svcDirs = await listServiceDirs(outDir);
  for (const svcDir of svcDirs) {
    const docsDir = join(svcDir, "docs");
    for await (const file of walkMd(docsDir)) {
      const rel = joinUnix(relative(docsDir, file));
      if (!(SERVICE_DOCS_WHITELIST as readonly string[]).includes(rel)) continue;
      const content = await readFile(file, "utf8");
      const svcName = relative(outDir, svcDir).split(/[\\/]/).pop() ?? "";
      entries.push({
        path: joinUnix(relative(outDir, file)),
        scope: "service",
        serviceId: svcName,
        kind: rel.replace(/\.md$/, ""),
        phase: opts.phase ?? 5,
        sha256: sha256(content),
        generatedAt: new Date().toISOString(),
      });
    }
  }

  return entries.sort((a, b) => a.path.localeCompare(b.path));
}

export function renderRegistryMd(entries: RegistryEntry[]): string {
  const lines: string[] = [];
  lines.push("# Documentation Registry");
  lines.push("");
  lines.push(
    "This file is generated by `architect verify` (and Phase 7 of `architect new`). " +
      "It is the authoritative whitelist of every documentation artifact in this project. " +
      "If a `.md` file is missing here or appears here without a matching file on disk, " +
      "`architect verify` will fail.",
  );
  lines.push("");
  lines.push(`**Entries:** ${entries.length}`);
  lines.push(`**Generated at:** ${new Date().toISOString()}`);
  lines.push("");
  lines.push("| Scope | Service | Kind | Path | Phase |");
  lines.push("|---|---|---|---|---|");
  for (const e of entries) {
    lines.push(`| ${e.scope} | ${e.serviceId ?? ""} | ${e.kind} | \`${e.path}\` | ${e.phase} |`);
  }
  lines.push("");
  return lines.join("\n");
}

function inferKindFromRoot(rel: string): { scope: RegistryEntry["scope"]; kind: string } | null {
  if ((ROOT_DOCS_WHITELIST as readonly string[]).includes(rel)) {
    if (rel.startsWith("architecture/"))
      return {
        scope: "architecture",
        kind: rel.slice("architecture/".length).replace(/\.md$/, ""),
      };
    if (rel.startsWith("qa/"))
      return { scope: "qa", kind: rel.slice("qa/".length).replace(/\.md$/, "") };
    if (rel.startsWith("research/"))
      return { scope: "research", kind: rel.slice("research/".length).replace(/\.md$/, "") };
    if (rel.startsWith("ui/"))
      return { scope: "ui", kind: rel.slice("ui/".length).replace(/\.md$/, "") };
    return { scope: "root", kind: rel.replace(/\.md$/, "") };
  }
  return null;
}

async function* walkMd(dir: string): AsyncGenerator<string, void, void> {
  const stack = [dir];
  while (stack.length > 0) {
    const cur = stack.pop();
    if (!cur) break;
    let entries: import("node:fs").Dirent[];
    try {
      entries = await readdir(cur, { withFileTypes: true });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") continue;
      throw err;
    }
    for (const ent of entries) {
      const p = join(cur, ent.name);
      if (ent.isDirectory()) stack.push(p);
      else if (ent.isFile() && ent.name.endsWith(".md")) yield p;
    }
  }
}

async function listServiceDirs(outDir: string): Promise<string[]> {
  // A "service dir" is any directory at depth 2 from outDir that contains a docs/ subdir.
  // outDir/<domain>/<service>/docs/   OR   outDir/<service>/docs/
  const found: string[] = [];
  const seen = new Set<string>();

  async function* walk(d: string, depth: number): AsyncGenerator<string, void, void> {
    if (depth > 3) return;
    let entries: import("node:fs").Dirent[];
    try {
      entries = await readdir(d, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      if (e.name === "docs" || e.name.startsWith(".") || e.name === "node_modules") continue;
      const next = join(d, e.name);
      if (next === join(outDir, "docs")) continue;
      const docsDir = join(next, "docs");
      try {
        const ds = await readdir(docsDir);
        if (ds.length > 0 && !seen.has(next)) {
          seen.add(next);
          yield next;
        }
      } catch {
        // not a service dir; recurse
        for await (const x of walk(next, depth + 1)) yield x;
      }
    }
  }

  for await (const svc of walk(outDir, 0)) {
    found.push(svc);
  }
  return found;
}
